FROM python:3.8

WORKDIR /usr/src/my_site
COPY requirements.txt .

RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get install -y nodejs
WORKDIR /usr/src/my_site/common/static/common/js
RUN npm install -y
WORKDIR /usr/src/my_site

EXPOSE 8000
CMD sh init.sh && python3 manage.py runserver 0.0.0.0:8000
